### ISSUE TITLE
RuntimeException : folder ... /blueprints/ was not found

### ISSUE THREAD

**Issue by Ali-RS** [methusalah/alchemist#20]
Hi @methusalah 
Just cloned this project and built it. 
When running i am getting this error stack : 

```
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: javafx.fxml.LoadException: 
file:/media/idea/My%20Passport/Java/jME_NB-PW-11-6-2015/alchemist/build/libs/alchemist.jar!/com/brainless/alchemist/view/overview/Overview.fxml

	at com.brainless.alchemist.view.util.ViewLoader.loadFXMLForControl(ViewLoader.java:42)
	at com.brainless.alchemist.view.overview.Overview.<init>(Overview.java:22)
	at com.brainless.alchemist.view.Alchemist.start(Alchemist.java:45)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	... 1 more
Caused by: javafx.fxml.LoadException: 
file:/media/idea/My%20Passport/Java/jME_NB-PW-11-6-2015/alchemist/build/libs/alchemist.jar!/com/brainless/alchemist/view/overview/Overview.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2601)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2571)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at com.brainless.alchemist.view.util.ViewLoader.loadFXMLForControl(ViewLoader.java:39)
	... 11 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2566)
	... 14 more
Caused by: java.lang.ExceptionInInitializerError
	at com.brainless.alchemist.presentation.resources.ResourcesPresenter.<init>(ResourcesPresenter.java:25)
	at com.brainless.alchemist.view.tab.resources.Resources.<init>(Resources.java:17)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at sun.reflect.misc.ReflectUtil.newInstance(ReflectUtil.java:51)
	at javafx.fxml.FXMLLoader$InstanceDeclarationElement.constructValue(FXMLLoader.java:1009)
	at javafx.fxml.FXMLLoader$ValueElement.processStartElement(FXMLLoader.java:746)
	at javafx.fxml.FXMLLoader.processStartElement(FXMLLoader.java:2707)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2527)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2441)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:2409)
	at com.brainless.alchemist.view.util.ViewLoader.loadFXMLForControl(ViewLoader.java:39)
	at com.brainless.alchemist.view.tab.resources.ResourcesTab.<init>(ResourcesTab.java:11)
	at com.brainless.alchemist.view.overview.Overview.initialize(Overview.java:36)
	... 24 more
Caused by: java.lang.RuntimeException: the folder /media/idea/My%20Passport/Java/jME_NB-PW-11-6-2015/alchemist/sampleProject/build/resources/main/data/blueprints/ was not found.
	at com.brainless.alchemist.model.ECS.blueprint.BlueprintLibrary.getFilesDeeply(BlueprintLibrary.java:73)
	at com.brainless.alchemist.model.ECS.blueprint.BlueprintLibrary.loadBlueprints(BlueprintLibrary.java:60)
	at com.brainless.alchemist.model.ECS.blueprint.BlueprintLibrary.<clinit>(BlueprintLibrary.java:36)
	... 41 more
Exception running application app.MainSample
AL lib: (EE) alc_cleanup: 1 device not closed
pure virtual method called
terminate called without an active exception
:sampleProject:run FAILED

```

But the folder /media/idea/My%20Passport/Java/jME_NB-PW-11-6-2015/alchemist/sampleProject/build/resources/main/data/blueprints/ is already there and contains all `.blueprint` files. 

Should i add that path as runtime file dependency in gradle ? how ?

Thanks

**Comment by methusalah** [comment]
It seems that it fails to load the design files as well (but it's not a blocking exception).

It may be a path issue. Please test moving the project into a shorter path, or without special caracter.

**Comment by Ali-RS** [comment]
That just worked. Thanks.
