### ISSUE TITLE
Bad compile of: MyTerrainLighting shader

### ISSUE THREAD

**Issue by Ali-RS** [methusalah/alchemist#21]
Hi again. 

When running `sampleProject` i am getting shader compile error. Thought to make an issue about it. 
Sorry i have not worked with shaders before. 

```
WARNING: Bad compile of:
1	#version 110
2	#define FRAGMENT_SHADER 1
3	#define DIFFUSEMAP 1
4	#define DIFFUSEMAP_1 1
5	#define DIFFUSEMAP_2 1
6	#define DIFFUSEMAP_3 1
7	#define DIFFUSEMAP_4 1
8	#define DIFFUSEMAP_5 1
9	#define DIFFUSEMAP_6 1
10	#define DIFFUSEMAP_7 1
11	#define ALPHAMAP 1
12	#define ALPHAMAP_1 1
13	#define DIFFUSEMAP_0_SCALE 8.0
14	#define DIFFUSEMAP_1_SCALE 32.0
15	#define DIFFUSEMAP_2_SCALE 32.0
16	
17	uniform float m_Shininess;
18	uniform vec4 g_LightDirection;
19	
20	varying vec4 AmbientSum;
21	varying vec4 DiffuseSum;
22	varying vec4 SpecularSum;
23	
24	varying vec3 vNormal;
25	varying vec2 texCoord;
26	varying vec3 vPosition;
27	varying vec3 vnPosition;
28	varying vec3 vViewDir;
29	varying vec4 vLightDir;
30	varying vec4 vnLightDir;
31	varying vec3 lightVec;
32	
33	
34	#ifdef DIFFUSEMAP
35	  uniform sampler2D m_DiffuseMap;
36	#endif
37	#ifdef DIFFUSEMAP_1
38	  uniform sampler2D m_DiffuseMap_1;
39	#endif
40	#ifdef DIFFUSEMAP_2
41	  uniform sampler2D m_DiffuseMap_2;
42	#endif
43	#ifdef DIFFUSEMAP_3
44	  uniform sampler2D m_DiffuseMap_3;
45	#endif
46	#ifdef DIFFUSEMAP_4
47	  uniform sampler2D m_DiffuseMap_4;
48	#endif
49	#ifdef DIFFUSEMAP_5
50	  uniform sampler2D m_DiffuseMap_5;
51	#endif
52	#ifdef DIFFUSEMAP_6
53	  uniform sampler2D m_DiffuseMap_6;
54	#endif
55	#ifdef DIFFUSEMAP_7
56	  uniform sampler2D m_DiffuseMap_7;
57	#endif
58	#ifdef DIFFUSEMAP_8
59	  uniform sampler2D m_DiffuseMap_8;
60	#endif
61	#ifdef DIFFUSEMAP_9
62	  uniform sampler2D m_DiffuseMap_9;
63	#endif
64	#ifdef DIFFUSEMAP_10
65	  uniform sampler2D m_DiffuseMap_10;
66	#endif
67	#ifdef DIFFUSEMAP_11
68	  uniform sampler2D m_DiffuseMap_11;
69	#endif
70	
71	
72	#ifdef DIFFUSEMAP_0_SCALE
73	  uniform float m_DiffuseMap_0_scale;
74	#endif
75	#ifdef DIFFUSEMAP_1_SCALE
76	  uniform float m_DiffuseMap_1_scale;
77	#endif
78	#ifdef DIFFUSEMAP_2_SCALE
79	  uniform float m_DiffuseMap_2_scale;
80	#endif
81	#ifdef DIFFUSEMAP_3_SCALE
82	  uniform float m_DiffuseMap_3_scale;
83	#endif
84	#ifdef DIFFUSEMAP_4_SCALE
85	  uniform float m_DiffuseMap_4_scale;
86	#endif
87	#ifdef DIFFUSEMAP_5_SCALE
88	  uniform float m_DiffuseMap_5_scale;
89	#endif
90	#ifdef DIFFUSEMAP_6_SCALE
91	  uniform float m_DiffuseMap_6_scale;
92	#endif
93	#ifdef DIFFUSEMAP_7_SCALE
94	  uniform float m_DiffuseMap_7_scale;
95	#endif
96	#ifdef DIFFUSEMAP_8_SCALE
97	  uniform float m_DiffuseMap_8_scale;
98	#endif
99	#ifdef DIFFUSEMAP_9_SCALE
100	  uniform float m_DiffuseMap_9_scale;
101	#endif
102	#ifdef DIFFUSEMAP_10_SCALE
103	  uniform float m_DiffuseMap_10_scale;
104	#endif
105	#ifdef DIFFUSEMAP_11_SCALE
106	  uniform float m_DiffuseMap_11_scale;
107	#endif
108	
109	
110	#ifdef ALPHAMAP
111	  uniform sampler2D m_AlphaMap;
112	#endif
113	#ifdef ALPHAMAP_1
114	  uniform sampler2D m_AlphaMap_1;
115	#endif
116	#ifdef ALPHAMAP_2
117	  uniform sampler2D m_AlphaMap_2;
118	#endif
119	
120	#ifdef NORMALMAP
121	  uniform sampler2D m_NormalMap;
122	#endif
123	#ifdef NORMALMAP_1
124	  uniform sampler2D m_NormalMap_1;
125	#endif
126	#ifdef NORMALMAP_2
127	  uniform sampler2D m_NormalMap_2;
128	#endif
129	#ifdef NORMALMAP_3
130	  uniform sampler2D m_NormalMap_3;
131	#endif
132	#ifdef NORMALMAP_4
133	  uniform sampler2D m_NormalMap_4;
134	#endif
135	#ifdef NORMALMAP_5
136	  uniform sampler2D m_NormalMap_5;
137	#endif
138	#ifdef NORMALMAP_6
139	  uniform sampler2D m_NormalMap_6;
140	#endif
141	#ifdef NORMALMAP_7
142	  uniform sampler2D m_NormalMap_7;
143	#endif
144	#ifdef NORMALMAP_8
145	  uniform sampler2D m_NormalMap_8;
146	#endif
147	#ifdef NORMALMAP_9
148	  uniform sampler2D m_NormalMap_9;
149	#endif
150	#ifdef NORMALMAP_10
151	  uniform sampler2D m_NormalMap_10;
152	#endif
153	#ifdef NORMALMAP_11
154	  uniform sampler2D m_NormalMap_11;
155	#endif
156	
157	
158	#ifdef TRI_PLANAR_MAPPING
159	  varying vec4 wVertex;
160	  varying vec3 wNormal;
161	#endif
162	
163	
164	
165	float tangDot(in vec3 v1, in vec3 v2){
166	    float d = dot(v1,v2);
167	    #ifdef V_TANGENT
168	        d = 1.0 - d*d;
169	        return step(0.0, d) * sqrt(d);
170	    #else
171	        return d;
172	    #endif
173	}
174	
175	
176	float lightComputeDiffuse(in vec3 norm, in vec3 lightdir, in vec3 viewdir){
177	    return max(0.0, dot(norm, lightdir));
178	}
179	
180	float lightComputeSpecular(in vec3 norm, in vec3 viewdir, in vec3 lightdir, in float shiny){
181	    #ifdef WARDISO
182	        // Isotropic Ward
183	        vec3 halfVec = normalize(viewdir + lightdir);
184	        float NdotH  = max(0.001, tangDot(norm, halfVec));
185	        float NdotV  = max(0.001, tangDot(norm, viewdir));
186	        float NdotL  = max(0.001, tangDot(norm, lightdir));
187	        float a      = tan(acos(NdotH));
188	        float p      = max(shiny/128.0, 0.001);
189	        return NdotL * (1.0 / (4.0*3.14159265*p*p)) * (exp(-(a*a)/(p*p)) / (sqrt(NdotV * NdotL)));
190	    #else
191	       // Standard Phong
192	       vec3 R = reflect(-lightdir, norm);
193	       return pow(max(tangDot(R, viewdir), 0.0), shiny);
194	    #endif
195	}
196	
197	vec2 computeLighting(in vec3 wvPos, in vec3 wvNorm, in vec3 wvViewDir, in vec3 wvLightDir){
198	   float diffuseFactor = lightComputeDiffuse(wvNorm, wvLightDir, wvViewDir);
199	   float specularFactor = lightComputeSpecular(wvNorm, wvViewDir, wvLightDir, m_Shininess);
200	
201	   if (m_Shininess <= 1.0) {
202	       specularFactor = 0.0; // should be one instruction on most cards ..
203	   }
204	
205	   float att = vLightDir.w;
206	
207	   return vec2(diffuseFactor, specularFactor) * vec2(att);
208	}
209	
210	
211	#ifdef ALPHAMAP
212	
213	  vec4 calculateDiffuseBlend(in vec2 texCoord) {
214	    vec4 alphaBlend   = texture2D( m_AlphaMap, texCoord.xy );
215	    
216	    #ifdef ALPHAMAP_1
217	      vec4 alphaBlend1   = texture2D( m_AlphaMap_1, texCoord.xy );
218	    #endif
219	    #ifdef ALPHAMAP_2
220	      vec4 alphaBlend2   = texture2D( m_AlphaMap_2, texCoord.xy );
221	    #endif
222	
223	    vec4 diffuseColor0 = texture2D(m_DiffuseMap, texCoord * m_DiffuseMap_0_scale);
224	    float transp = (1.0-diffuseColor0.a)*alphaBlend.r;
225	    vec4 diffuseColor = diffuseColor0*alphaBlend.r;
226	    
227	    #ifdef DIFFUSEMAP_1
228	      vec4 diffuseColor1 = texture2D(m_DiffuseMap_1, texCoord * m_DiffuseMap_1_scale);
229	      transp += (1.0-diffuseColor1.a)*alphaBlend.g;
230	      diffuseColor = mix( diffuseColor, diffuseColor1, alphaBlend.g );
231	    
232	      #ifdef DIFFUSEMAP_2
233	        vec4 diffuseColor2 = texture2D(m_DiffuseMap_2, texCoord * m_DiffuseMap_2_scale);
234	      	transp += (1.0-diffuseColor2.a)*alphaBlend.b;
235	      	diffuseColor = mix( diffuseColor, diffuseColor2, alphaBlend.b );
236	    
237	        #ifdef DIFFUSEMAP_3
238	          vec4 diffuseColor3 = texture2D(m_DiffuseMap_3, texCoord * m_DiffuseMap_3_scale);
239	     	  transp += (1.0-diffuseColor3.a)*alphaBlend.a;
240	          diffuseColor = mix( diffuseColor, diffuseColor3, alphaBlend.a );
241	    
242	          #ifdef ALPHAMAP_1
243	              #ifdef DIFFUSEMAP_4
244	                vec4 diffuseColor4 = texture2D(m_DiffuseMap_4, texCoord * m_DiffuseMap_4_scale);
245	      			transp += (1.0-diffuseColor4.a)*alphaBlend1.r;
246	                diffuseColor = mix( diffuseColor, diffuseColor4, alphaBlend1.r );
247	    
248	                #ifdef DIFFUSEMAP_5
249	                  vec4 diffuseColor5 = texture2D(m_DiffuseMap_5, texCoord * m_DiffuseMap_5_scale);
250				      transp += (1.0-diffuseColor5.a)*alphaBlend1.g;
251	                  diffuseColor = mix( diffuseColor, diffuseColor5, alphaBlend1.g );
252	                  
253	                  #ifdef DIFFUSEMAP_6
254	                    vec4 diffuseColor6 = texture2D(m_DiffuseMap_6, texCoord * m_DiffuseMap_6_scale);
255						transp += (1.0-diffuseColor6.a)*alphaBlend1.b;
256	                    diffuseColor = mix( diffuseColor, diffuseColor6, alphaBlend1.b );
257	                    
258	                    #ifdef DIFFUSEMAP_7
259	                      vec4 diffuseColor7 = texture2D(m_DiffuseMap_7, texCoord * m_DiffuseMap_7_scale);
260						  transp += (1.0-diffuseColor7.a)*alphaBlend1.a;
261	                      diffuseColor = mix( diffuseColor, diffuseColor7, alphaBlend1.a );
262	                      
263	                      
264	                      
265	                      
266	                      #ifdef ALPHAMAP_2
267	                          #ifdef DIFFUSEMAP_8
268	                            vec4 diffuseColor8 = texture2D(m_DiffuseMap_8, texCoord * m_DiffuseMap_8_scale);
269							    transp += diffuseColor8.a*alphaBlend2.r;
270	                            diffuseColor = mix( diffuseColor, diffuseColor8, alphaBlend2.r );
271	                            
272	                            #ifdef DIFFUSEMAP_9
273	                              vec4 diffuseColor9 = texture2D(m_DiffuseMap_9, texCoord * m_DiffuseMap_9_scale);
274	      						  transp += diffuseColor9.a*alphaBlend2.g;
275	                              diffuseColor = mix( diffuseColor, diffuseColor9, alphaBlend2.g );
276	                            
277	                              #ifdef DIFFUSEMAP_10
278	                                vec4 diffuseColor10 = texture2D(m_DiffuseMap_10, texCoord * m_DiffuseMap_10_scale);
279	  								transp += diffuseColor10.a*alphaBlend2.b;
280	                                diffuseColor = mix( diffuseColor, diffuseColor10, alphaBlend2.b );
281	                            
282	                                #ifdef DIFFUSEMAP_11
283	                                  vec4 diffuseColor11 = texture2D(m_DiffuseMap_11, texCoord * m_DiffuseMap_11_scale);
284	      							  transp += diffuseColor11.a*alphaBlend2.a;
285	                                  diffuseColor = mix( diffuseColor, diffuseColor11, alphaBlend2.a );
286	                                #endif
287	                              #endif
288	                            #endif
289	                          #endif
290	                      #endif
291	                    #endif
292	                  #endif
293	                #endif
294	              #endif
295	          #endif
296	        #endif
297	      #endif
298	    #endif
299	    diffuseColor.a = 1.0-transp;
300	    return diffuseColor;
301	  }
302	
303	  vec3 calculateNormal(in vec2 texCoord) {
304	    vec3 normal = vec3(0,0,1);
305	    vec3 n = vec3(0,0,0);
306	
307	    vec4 alphaBlend = texture2D( m_AlphaMap, texCoord.xy );
308	
309	    #ifdef ALPHAMAP_1
310	      vec4 alphaBlend1 = texture2D( m_AlphaMap_1, texCoord.xy );
311	    #endif
312	    #ifdef ALPHAMAP_2
313	      vec4 alphaBlend2 = texture2D( m_AlphaMap_2, texCoord.xy );
314	    #endif
315	
316	    #ifdef NORMALMAP
317	      n = texture2D(m_NormalMap, texCoord * m_DiffuseMap_0_scale).xyz;
318	      normal += n * alphaBlend.r;
319	    #else
320	      normal += vec3(0.5,0.5,1) * alphaBlend.r;
321	    #endif
322	
323	    #ifdef NORMALMAP_1
324	      n = texture2D(m_NormalMap_1, texCoord * m_DiffuseMap_1_scale).xyz;
325	      normal += n * alphaBlend.g;
326	    #else
327	      normal += vec3(0.5,0.5,1) * alphaBlend.g;
328	    #endif
329	
330	    #ifdef NORMALMAP_2
331	      n = texture2D(m_NormalMap_2, texCoord * m_DiffuseMap_2_scale).xyz;
332	      normal += n * alphaBlend.b;
333	    #else
334	      normal += vec3(0.5,0.5,1) * alphaBlend.b;
335	    #endif
336	
337	    #ifdef NORMALMAP_3
338	      n = texture2D(m_NormalMap_3, texCoord * m_DiffuseMap_3_scale).xyz;
339	      normal += n * alphaBlend.a;
340	    #else
341	      normal += vec3(0.5,0.5,1) * alphaBlend.a;
342	    #endif
343	
344	    #ifdef ALPHAMAP_1
345	        #ifdef NORMALMAP_4
346	          n = texture2D(m_NormalMap_4, texCoord * m_DiffuseMap_4_scale).xyz;
347	          normal += n * alphaBlend1.r;
348	        #endif
349	
350	        #ifdef NORMALMAP_5
351	          n = texture2D(m_NormalMap_5, texCoord * m_DiffuseMap_5_scale).xyz;
352	          normal += n * alphaBlend1.g;
353	        #endif
354	
355	        #ifdef NORMALMAP_6
356	          n = texture2D(m_NormalMap_6, texCoord * m_DiffuseMap_6_scale).xyz;
357	          normal += n * alphaBlend1.b;
358	        #endif
359	
360	        #ifdef NORMALMAP_7
361	          n = texture2D(m_NormalMap_7, texCoord * m_DiffuseMap_7_scale).xyz;
362	          normal += n * alphaBlend1.a;
363	        #endif
364	    #endif
365	
366	    #ifdef ALPHAMAP_2
367	        #ifdef NORMALMAP_8
368	          n = texture2D(m_NormalMap_8, texCoord * m_DiffuseMap_8_scale).xyz;
369	          normal += n * alphaBlend2.r;
370	        #endif
371	
372	        #ifdef NORMALMAP_9
373	          n = texture2D(m_NormalMap_9, texCoord * m_DiffuseMap_9_scale);
374	          normal += n * alphaBlend2.g;
375	        #endif
376	
377	        #ifdef NORMALMAP_10
378	          n = texture2D(m_NormalMap_10, texCoord * m_DiffuseMap_10_scale);
379	          normal += n * alphaBlend2.b;
380	        #endif
381	
382	        #ifdef NORMALMAP_11
383	          n = texture2D(m_NormalMap_11, texCoord * m_DiffuseMap_11_scale);
384	          normal += n * alphaBlend2.a;
385	        #endif
386	    #endif
387	
388	    normal = (normal.xyz * vec3(2.0) - vec3(1.0));
389	    return normalize(normal);
390	  }
391	
392	  #ifdef TRI_PLANAR_MAPPING
393	
394	    vec4 getTriPlanarBlend(in vec4 coords, in vec3 blending, in sampler2D map, in float scale) {
395	      vec4 col1 = texture2D( map, coords.yz * scale);
396	      vec4 col2 = texture2D( map, coords.xz * scale);
397	      vec4 col3 = texture2D( map, coords.xy * scale);
398	      // blend the results of the 3 planar projections.
399	      vec4 tex = col1 * blending.x + col2 * blending.y + col3 * blending.z;
400	      return tex;
401	    }
402	
403	    vec4 calculateTriPlanarDiffuseBlend(in vec3 wNorm, in vec4 wVert, in vec2 texCoord) {
404	        // tri-planar texture bending factor for this fragment's normal
405	        vec3 blending = abs( wNorm );
406	        blending = (blending -0.2) * 0.7;
407	        blending = normalize(max(blending, 0.00001));      // Force weights to sum to 1.0 (very important!)
408	        float b = (blending.x + blending.y + blending.z);
409	        blending /= vec3(b, b, b);
410	
411	        // texture coords
412	        vec4 coords = wVert;
413	
414	        // blend the results of the 3 planar projections.
415	        vec4 tex0 = getTriPlanarBlend(coords, blending, m_DiffuseMap, m_DiffuseMap_0_scale);
416	
417	        #ifdef DIFFUSEMAP_1
418	          // blend the results of the 3 planar projections.
419	          vec4 tex1 = getTriPlanarBlend(coords, blending, m_DiffuseMap_1, m_DiffuseMap_1_scale);
420	        #endif
421	        #ifdef DIFFUSEMAP_2
422	          // blend the results of the 3 planar projections.
423	          vec4 tex2 = getTriPlanarBlend(coords, blending, m_DiffuseMap_2, m_DiffuseMap_2_scale);
424	        #endif
425	        #ifdef DIFFUSEMAP_3
426	          // blend the results of the 3 planar projections.
427	          vec4 tex3 = getTriPlanarBlend(coords, blending, m_DiffuseMap_3, m_DiffuseMap_3_scale);
428	        #endif
429	        #ifdef DIFFUSEMAP_4
430	          // blend the results of the 3 planar projections.
431	          vec4 tex4 = getTriPlanarBlend(coords, blending, m_DiffuseMap_4, m_DiffuseMap_4_scale);
432	        #endif
433	        #ifdef DIFFUSEMAP_5
434	          // blend the results of the 3 planar projections.
435	          vec4 tex5 = getTriPlanarBlend(coords, blending, m_DiffuseMap_5, m_DiffuseMap_5_scale);
436	        #endif
437	        #ifdef DIFFUSEMAP_6
438	          // blend the results of the 3 planar projections.
439	          vec4 tex6 = getTriPlanarBlend(coords, blending, m_DiffuseMap_6, m_DiffuseMap_6_scale);
440	        #endif
441	        #ifdef DIFFUSEMAP_7
442	          // blend the results of the 3 planar projections.
443	          vec4 tex7 = getTriPlanarBlend(coords, blending, m_DiffuseMap_7, m_DiffuseMap_7_scale);
444	        #endif
445	        #ifdef DIFFUSEMAP_8
446	          // blend the results of the 3 planar projections.
447	          vec4 tex8 = getTriPlanarBlend(coords, blending, m_DiffuseMap_8, m_DiffuseMap_8_scale);
448	        #endif
449	        #ifdef DIFFUSEMAP_9
450	          // blend the results of the 3 planar projections.
451	          vec4 tex9 = getTriPlanarBlend(coords, blending, m_DiffuseMap_9, m_DiffuseMap_9_scale);
452	        #endif
453	        #ifdef DIFFUSEMAP_10
454	          // blend the results of the 3 planar projections.
455	          vec4 tex10 = getTriPlanarBlend(coords, blending, m_DiffuseMap_10, m_DiffuseMap_10_scale);
456	        #endif
457	        #ifdef DIFFUSEMAP_11
458	          // blend the results of the 3 planar projections.
459	          vec4 tex11 = getTriPlanarBlend(coords, blending, m_DiffuseMap_11, m_DiffuseMap_11_scale);
460	        #endif
461	
462	        vec4 alphaBlend   = texture2D( m_AlphaMap, texCoord.xy );
463	
464	        #ifdef ALPHAMAP_1
465	          vec4 alphaBlend1   = texture2D( m_AlphaMap_1, texCoord.xy );
466	        #endif
467	        #ifdef ALPHAMAP_2
468	          vec4 alphaBlend2   = texture2D( m_AlphaMap_2, texCoord.xy );
469	        #endif
470	
471	        vec4 diffuseColor = tex0 * alphaBlend.r;
472	        #ifdef DIFFUSEMAP_1
473	          diffuseColor = mix( diffuseColor, tex1, alphaBlend.g );
474	          #ifdef DIFFUSEMAP_2
475	            diffuseColor = mix( diffuseColor, tex2, alphaBlend.b );
476	            #ifdef DIFFUSEMAP_3
477	              diffuseColor = mix( diffuseColor, tex3, alphaBlend.a );
478	              #ifdef ALPHAMAP_1
479	                  #ifdef DIFFUSEMAP_4
480	                    diffuseColor = mix( diffuseColor, tex4, alphaBlend1.r );
481	                    #ifdef DIFFUSEMAP_5
482	                      diffuseColor = mix( diffuseColor, tex5, alphaBlend1.g );
483	                      #ifdef DIFFUSEMAP_6
484	                        diffuseColor = mix( diffuseColor, tex6, alphaBlend1.b );
485	                        #ifdef DIFFUSEMAP_7
486	                          diffuseColor = mix( diffuseColor, tex7, alphaBlend1.a );
487	                          #ifdef ALPHAMAP_2
488	                              #ifdef DIFFUSEMAP_8
489	                                diffuseColor = mix( diffuseColor, tex8, alphaBlend2.r );
490	                                #ifdef DIFFUSEMAP_9
491	                                  diffuseColor = mix( diffuseColor, tex9, alphaBlend2.g );
492	                                  #ifdef DIFFUSEMAP_10
493	                                    diffuseColor = mix( diffuseColor, tex10, alphaBlend2.b );
494	                                    #ifdef DIFFUSEMAP_11
495	                                      diffuseColor = mix( diffuseColor, tex11, alphaBlend2.a );
496	                                    #endif
497	                                  #endif
498	                                #endif
499	                              #endif
500	                          #endif
501	                        #endif
502	                      #endif
503	                    #endif
504	                  #endif
505	              #endif
506	            #endif
507	          #endif
508	        #endif
509	
510	        return diffuseColor;
511	    }
512	
513	    vec3 calculateNormalTriPlanar(in vec3 wNorm, in vec4 wVert,in vec2 texCoord) {
514	      // tri-planar texture bending factor for this fragment's world-space normal
515	      vec3 blending = abs( wNorm );
516	      blending = (blending -0.2) * 0.7;
517	      blending = normalize(max(blending, 0.00001));      // Force weights to sum to 1.0 (very important!)
518	      float b = (blending.x + blending.y + blending.z);
519	      blending /= vec3(b, b, b);
520	
521	      // texture coords
522	      vec4 coords = wVert;
523	      vec4 alphaBlend = texture2D( m_AlphaMap, texCoord.xy );
524	
525	      #ifdef ALPHAMAP_1
526	        vec4 alphaBlend1 = texture2D( m_AlphaMap_1, texCoord.xy );
527	      #endif
528	      #ifdef ALPHAMAP_2
529	        vec4 alphaBlend2 = texture2D( m_AlphaMap_2, texCoord.xy );
530	      #endif
531	
532	      vec3 normal = vec3(0,0,1);
533	      vec3 n = vec3(0,0,0);
534	
535	      #ifdef NORMALMAP
536	          n = getTriPlanarBlend(coords, blending, m_NormalMap, m_DiffuseMap_0_scale).xyz;
537	          normal += n * alphaBlend.r;
538	      #else
539	          normal += vec3(0.5,0.5,1) * alphaBlend.r;
540	      #endif
541	
542	      #ifdef NORMALMAP_1
543	          n = getTriPlanarBlend(coords, blending, m_NormalMap_1, m_DiffuseMap_1_scale).xyz;
544	          normal += n * alphaBlend.g;
545	      #else
546	          normal += vec3(0.5,0.5,1) * alphaBlend.g;
547	      #endif
548	
549	      #ifdef NORMALMAP_2
550	          n = getTriPlanarBlend(coords, blending, m_NormalMap_2, m_DiffuseMap_2_scale).xyz;
551	          normal += n * alphaBlend.b;
552	      #else
553	          normal += vec3(0.5,0.5,1) * alphaBlend.b;
554	      #endif
555	
556	      #ifdef NORMALMAP_3
557	          n = getTriPlanarBlend(coords, blending, m_NormalMap_3, m_DiffuseMap_3_scale).xyz;
558	          normal += n * alphaBlend.a;
559	      #else
560	          normal += vec3(0.5,0.5,1) * alphaBlend.a;
561	      #endif
562	
563	      #ifdef ALPHAMAP_1
564	          #ifdef NORMALMAP_4
565	              n = getTriPlanarBlend(coords, blending, m_NormalMap_4, m_DiffuseMap_4_scale).xyz;
566	              normal += n * alphaBlend1.r;
567	          #else
568	              normal += vec3(0.5,0.5,1) * alphaBlend.r;
569	          #endif
570	
571	          #ifdef NORMALMAP_5
572	              n = getTriPlanarBlend(coords, blending, m_NormalMap_5, m_DiffuseMap_5_scale).xyz;
573	              normal += n * alphaBlend1.g;
574	          #else
575	              normal += vec3(0.5,0.5,1) * alphaBlend.g;
576	          #endif
577	
578	          #ifdef NORMALMAP_6
579	              n = getTriPlanarBlend(coords, blending, m_NormalMap_6, m_DiffuseMap_6_scale).xyz;
580	              normal += n * alphaBlend1.b;
581	          #else
582	              normal += vec3(0.5,0.5,1) * alphaBlend.b;
583	          #endif
584	
585	          #ifdef NORMALMAP_7
586	              n = getTriPlanarBlend(coords, blending, m_NormalMap_7, m_DiffuseMap_7_scale).xyz;
587	              normal += n * alphaBlend1.a;
588	          #else
589	              normal += vec3(0.5,0.5,1) * alphaBlend.a;
590	          #endif
591	      #endif
592	
593	      #ifdef ALPHAMAP_2
594	          #ifdef NORMALMAP_8
595	              n = getTriPlanarBlend(coords, blending, m_NormalMap_8, m_DiffuseMap_8_scale).xyz;
596	              normal += n * alphaBlend2.r;
597	          #else
598	              normal += vec3(0.5,0.5,1) * alphaBlend.r;
599	          #endif
600	
601	          #ifdef NORMALMAP_9
602	              n = getTriPlanarBlend(coords, blending, m_NormalMap_9, m_DiffuseMap_9_scale).xyz;
603	              normal += n * alphaBlend2.g;
604	          #else
605	              normal += vec3(0.5,0.5,1) * alphaBlend.g;
606	          #endif
607	
608	          #ifdef NORMALMAP_10
609	              n = getTriPlanarBlend(coords, blending, m_NormalMap_10, m_DiffuseMap_10_scale).xyz;
610	              normal += n * alphaBlend2.b;
611	          #else
612	              normal += vec3(0.5,0.5,1) * alphaBlend.b;
613	          #endif
614	
615	          #ifdef NORMALMAP_11
616	              n = getTriPlanarBlend(coords, blending, m_NormalMap_11, m_DiffuseMap_11_scale).xyz;
617	              normal += n * alphaBlend2.a;
618	          #else
619	              normal += vec3(0.5,0.5,1) * alphaBlend.a;
620	          #endif
621	      #endif
622	
623	      normal = (normal.xyz * vec3(2.0) - vec3(1.0));
624	      return normalize(normal);
625	    }
626	  #endif
627	
628	#endif
629	
630	
631	
632	void main(){
633	
634	    //----------------------
635	    // diffuse calculations
636	    //----------------------
637	    #ifdef DIFFUSEMAP
638	      #ifdef ALPHAMAP
639	        #ifdef TRI_PLANAR_MAPPING
640	            vec4 diffuseColor = calculateTriPlanarDiffuseBlend(wNormal, wVertex, texCoord);
641	        #else
642	            vec4 diffuseColor = calculateDiffuseBlend(texCoord);
643	        #endif
644	      #else
645	        vec4 diffuseColor = texture2D(m_DiffuseMap, texCoord);
646	      #endif
647	    #else
648	      vec4 diffuseColor = vec4(1.0);
649	    #endif
650	
651	        float spotFallOff = 1.0;
652	        if(g_LightDirection.w!=0.0){
653	              vec3 L=normalize(lightVec.xyz);
654	              vec3 spotdir = normalize(g_LightDirection.xyz);
655	              float curAngleCos = dot(-L, spotdir);             
656	              float innerAngleCos = floor(g_LightDirection.w) * 0.001;
657	              float outerAngleCos = fract(g_LightDirection.w);
658	              float innerMinusOuter = innerAngleCos - outerAngleCos;
659	
660	              spotFallOff = (curAngleCos - outerAngleCos) / innerMinusOuter;
661	
662	              if(spotFallOff <= 0.0){
663	                  gl_FragColor = AmbientSum * diffuseColor;
664	                  return;
665	              }else{
666	                  spotFallOff = clamp(spotFallOff, 0.0, 1.0);
667	              }
668	        }
669	    
670	    //---------------------
671	    // normal calculations
672	    //---------------------
673	    #if defined(NORMALMAP) || defined(NORMALMAP_1) || defined(NORMALMAP_2) || defined(NORMALMAP_3) || defined(NORMALMAP_4) || defined(NORMALMAP_5) || defined(NORMALMAP_6) || defined(NORMALMAP_7) || defined(NORMALMAP_8) || defined(NORMALMAP_9) || defined(NORMALMAP_10) || defined(NORMALMAP_11)
674	      #ifdef TRI_PLANAR_MAPPING
675	        vec3 normal = calculateNormalTriPlanar(wNormal, wVertex, texCoord);
676	      #else
677	        vec3 normal = calculateNormal(texCoord);
678	      #endif
679	    #else
680	      vec3 normal = vNormal;
681	    #endif
682	
683	
684	    //-----------------------
685	    // lighting calculations
686	    //-----------------------
687	    vec4 lightDir = vLightDir;
688	    lightDir.xyz = normalize(lightDir.xyz);
689	
690	    vec2 light = computeLighting(vPosition, normal, vViewDir.xyz, lightDir.xyz)*spotFallOff;
691	
692	    vec4 specularColor = vec4(1.0);
693	
694	    //--------------------------
695	    // final color calculations
696	    //--------------------------
697	    gl_FragColor =  AmbientSum * diffuseColor +
698	                    DiffuseSum * diffuseColor  * light.x +
699	                    SpecularSum * specularColor * light.y;
700	
701	    //gl_FragColor.a = alpha;
702	}

Dec 12, 2016 12:34:40 PM com.jme3.app.LegacyApplication handleError
SEVERE: Uncaught exception thrown in Thread[jME3 Main,5,main]
com.jme3.renderer.RendererException: compile error in: ShaderSource[name=matdefs/MyTerrainLighting.frag, defines, type=Fragment, language=GLSL100]
0(238) : error C1008: undefined variable "m_DiffuseMap_3_scale"
0(244) : error C1008: undefined variable "m_DiffuseMap_4_scale"
0(249) : error C1008: undefined variable "m_DiffuseMap_5_scale"
0(254) : error C1008: undefined variable "m_DiffuseMap_6_scale"
0(259) : error C1008: undefined variable "m_DiffuseMap_7_scale"

	at com.jme3.renderer.opengl.GLRenderer.updateShaderSourceData(GLRenderer.java:1203)
	at com.jme3.renderer.opengl.GLRenderer.updateShaderData(GLRenderer.java:1230)
	at com.jme3.renderer.opengl.GLRenderer.setShader(GLRenderer.java:1294)
	at com.jme3.material.logic.MultiPassLightingLogic.render(MultiPassLightingLogic.java:176)
	at com.jme3.material.Technique.render(Technique.java:166)
	at com.jme3.material.Material.render(Material.java:970)
	at com.jme3.renderer.RenderManager.renderGeometry(RenderManager.java:616)
	at com.jme3.renderer.queue.RenderQueue.renderGeometryList(RenderQueue.java:266)
	at com.jme3.renderer.queue.RenderQueue.renderQueue(RenderQueue.java:305)
	at com.jme3.renderer.RenderManager.renderViewPortQueues(RenderManager.java:879)
	at com.jme3.renderer.RenderManager.flushQueue(RenderManager.java:781)
	at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:1106)
	at com.jme3.renderer.RenderManager.render(RenderManager.java:1154)
	at com.jme3.app.SimpleApplication.update(SimpleApplication.java:253)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.runLoop(LwjglOffscreenBuffer.java:125)
	at com.jme3.system.lwjgl.LwjglOffscreenBuffer.run(LwjglOffscreenBuffer.java:156)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by methusalah** [comment]
I've just pushed a fix

**Comment by Ali-RS** [comment]
Thanks.
